# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            XFireDB
tagline:          'XFireDB documentation'
description:      'XFireDB documentation'
url:              http://xfiredb.michelmegens.net
baseurl:          /

author:
  name:           'Michel Megens'
  url:            http://michelmegens.net

paginate:         5

# Custom vars
version:          1.0.0

github:
        repo:           http://git.bietje.net/xfiredb/xfiredb
